import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import process from "node:process";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";

export const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
// Generated by tests/setup.mjs before the suite runs.
export const FAKE_PLUGIN_ROOT = path.join(ROOT, "tests", ".generated", "plugins", "fake-bridge");
export const FAKE_SCRIPT = path.join(FAKE_PLUGIN_ROOT, "scripts", "bridge.mjs");
export const FAKE_DATA_ENV = "AGENT_BRIDGES_DATA_FAKE";
export const FAKE_SESSION_ENV = "AGENT_BRIDGES_SESSION_ID";

export function makeTempDir(prefix = "agent-bridges-test-") {
  return fs.mkdtempSync(path.join(os.tmpdir(), prefix));
}

export function writeExecutable(filePath, source) {
  fs.writeFileSync(filePath, source, { encoding: "utf8", mode: 0o755 });
}

export function run(command, args, options = {}) {
  return spawnSync(command, args, {
    cwd: options.cwd,
    env: options.env,
    encoding: "utf8",
    input: options.input,
    shell: options.shell ?? (process.platform === "win32" && !path.isAbsolute(command)),
    windowsHide: true
  });
}

export function runBridge(args, options = {}) {
  return run(process.execPath, [FAKE_SCRIPT, ...args], options);
}

export function initGitRepo(cwd) {
  run("git", ["init", "-b", "main"], { cwd });
  run("git", ["config", "user.name", "Agent Bridges Tests"], { cwd });
  run("git", ["config", "user.email", "tests@example.com"], { cwd });
  run("git", ["config", "commit.gpgsign", "false"], { cwd });
  run("git", ["config", "tag.gpgsign", "false"], { cwd });
  run("git", ["config", "core.autocrlf", "false"], { cwd });
}

/** Run `fn` with this process pointed at `dataDir` for the fake plugin's state. */
export function withPluginData(dataDir, fn) {
  const previous = process.env[FAKE_DATA_ENV];
  process.env[FAKE_DATA_ENV] = dataDir;
  const restore = () => {
    if (previous == null) {
      delete process.env[FAKE_DATA_ENV];
    } else {
      process.env[FAKE_DATA_ENV] = previous;
    }
  };
  try {
    const result = fn();
    if (result && typeof result.then === "function") {
      return result.finally(restore);
    }
    restore();
    return result;
  } catch (error) {
    restore();
    throw error;
  }
}
